name: Close Issue
on:
  issues:
    types: [opened]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.title, 'http')
      - name: Has_URL
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Thank you for submitting a URL.
            
            **Your URL can be found at: https://dont-ghost.me/${{ github.event.issue.number }}**
            
            Auto-closing this issue.

      - if: ${{failure()}}
      - name: No_URL
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            No URL found...
            
            Please make sure you have added `https://` to the beginning of your issue title.

            Auto-closing this issue.